version: '2'
services:
  gateway:
    image: spc-web-gateway
    tty: true
    ports:
      - "8088:8088"
      - "16000:16000"
    volumes:
      - etc/auth:/opt/spc-web-gateway/auth:z
      - etc/config.xml:/opt/spc-web-gateway/config.xml:ro
    restart: unless-stopped
    network_mode: host
